### ISSUE TITLE
Moans and voice do not work

### ISSUE THREAD

**Issue by anole44** [thefapinstructor/fapinstructor#20]
The moans and the voice that played before the video option no longer work

**Comment by ArtisticMenase** [comment]
This issue is cause by the audio context not being initialised before the audio file is retrieved, it seems the fetchAudioFile() method in the dictionary inside `audio/index.js` likes to resolve on startup, before the context is initialised, resulting in a return with no audio: 

`const fetchAudioFile = async url => {
  if (!contextCreated) {
    return;
  }
...
};`

It doesn't get called again on repeated dictionary access, so I've filed a pull request that _should_ fix this issue.

**Comment by thefapinstructor** [comment]
Merged PR  #22
