### ISSUE TITLE
Critical BUG: Tumblrs can't be empty

### ISSUE THREAD

**Issue by The1nstructor** [thefapinstructor/fapinstructor#40]
@ArtisticMenase what happens if no ID is specified?

**Comment by LenAnderson** [comment]
@The1nstructor 

`const tumblrIds` is assigned as `tumblrId.length && ...` which means for a config without Tumblrs it is `null`. The subsequent call to `tumblrIds.forEach` throws an uncaught exception (`null` has no `forEach`).

![Imgur](https://i.imgur.com/ijOtO0e.png)

**Comment by The1nstructor** [comment]
@LenAnderson You might create a PR with a bugfix for that issue. That would be very helpful!

**Comment by LenAnderson** [comment]
@The1nstructor I will once I manage to get the project to run properly. Tried it last night but it seems that a recent update to `@babel/runtime` broke some things and I could not start it by following the README instructions. Reverting to a previous version of babel worked but since I am new to node.js and npm I'm not sure I fixed it in the right place...

I'll add a PR once I feel that I know what I'm doing :)

**Comment by The1nstructor** [comment]
@LenAnderson If you face any further install problems just open up a new issue on GitHub. You probably won't be the only person having that problem. When I first installed it some stuff was missing, the npm error messages were quite helpful in that place.

**Comment by The1nstructor** [comment]
This problem is **STILL** present. 

Solution needed!
